spring:
  application:
    name: demo
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: "Hello World from DEV Tib"
  tools: "Hello Tools vous êtes les meilleurs depuis Dev Tib modif"
---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "Hello World from PROD Tib"
  tools: "Hello Tools depuis PROD Tib"
