spring:
  application:
    name: demo
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: "Hello World from DEV Tib"
---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "Hello World from PROD Tib"
